# Generated by Django 4.2.3 on 2023-07-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepaciente', models.CharField(max_length=100)),
                ('nivelazucar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivelgrasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('niveloxigeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('riesgo', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
